### ISSUE TITLE
full links

### ISSUE THREAD

**Issue by diomed** [Antes/TweetEmbed#1]
hi

could you possibly make this plugin to work with full links also?
It would be a lot easirer to just copy 

http://twitter.com/lucidchemistry/status/587750905778278400

and paste it, because there is button for Copy link to tweet, 
and removing adress parts is kinda waste of time.

**Comment by Antes** [comment]
Hello,

I guess you also mailed me yesterday, I thought I send a reply to you but, writing it here as well would be good. After version 1.1 (which is current stable) you can paste the link into your post, it'll auto-embed the tweet.

**Comment by diomed** [comment]
but when I write 
`[tweet]https://twitter.com/lucidchemistry/status/587750905778278400[/tweet]`
as I want it to be, it gives me back Invalid Tweet ID error

& I didn't mail you yesterday, but great minds think alike. haha. just kidding. :)
Though I'm glad more people would want that to be that way.

**Comment by Antes** [comment]
Ah I see, you don't need to use [tweet] tag when you are pasting full link. Just paste the link let the mod handle the rest :)

**Comment by Antes** [comment]
Hello

Modification had auto embed option, just paste the link. It will embed.

-----Original Message-----

**Comment by diomed** [comment]
yes, I get it now. Thank you. and I've already modified useless glow button to be [tweet] instead.
and now you say it's so simple I don't need any button, just link. haha 
Thank you! :smile_cat:
